variables:
  USR: root
  GIT_SUBMODULE_STRATEGY: recursive
  REMOTE_PATH: /usr/local/share/bot2
  PHP: /usr/bin/php8.4

.only_master: &only_master
  only:
    - master

stages:
  - install
  - deploy

build_composer:
  <<: *only_master
  stage: install
  variables:
    COMPOSER_PROCESS_TIMEOUT: "600"
    HTTP_PROXY: "$http_proxy"
    HTTPS_PROXY: "$http_proxy"
    NO_PROXY: "gitlab.novotelecom.ru,127.0.0.1,localhost"
  cache:
    key: "composer-${CI_COMMIT_REF_SLUG}"
    paths:
      - src/vendor/
  image: composer:2
  tags:
    - docker
  script:
    - cd src/
#    - export http_proxy="$http_proxy"
#    - export https_proxy="$http_proxy"
    - export COMPOSER_AUTH="{\"http-basic\":{\"gitlab.novotelecom.ru\":{\"username\":\"$LIBS_USER\",\"password\":\"$LIBS_PASS\"}}}"
    - /usr/bin/composer config repositories.libs '{"type":"vcs","url":"https://gitlab.novotelecom.ru/laravel-libs/libs.git","no-api":true}'
    - composer -V
    - composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-interaction
  artifacts:
    paths:
      - src/vendor/
    expire_in: 1 hour

.deploy_template: &deploy_definition
  <<: *only_master
  stage: deploy
  tags:
    - docker
  dependencies:
    - build_composer
  image: gitlab.novotelecom.ru:5050/otk/otk-service:latest
  script:
    - |
      echo "Checking artifacts..."
      if [ ! -d "src/vendor" ]; then
        echo "ERROR: src/vendor not found! Composer build failed or artifacts expired."
        exit 1
      fi
      echo "Artifacts are OK."

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$DEPLOYKEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERV >> ~/.ssh/known_hosts

#    - chmod +x env.sh
#    - ./env.sh
    - cd src/

    - >
      ssh $USR@$SERV "
        sudo mkdir -p $REMOTE_PATH &&
        sudo chown :www-data $REMOTE_PATH &&
        sudo chmod g+rw $REMOTE_PATH -R
      "

    # 1. Синхронизируем файлы (уже с vendor и build)
    - cd ..
    - rsync -avz --delete --exclude='.git/' --exclude='src/storage/*.key' src/ $USR@$SERV:$REMOTE_PATH/

    # 2. Настройка прав и кэша на сервере
    - >
      ssh $USR@$SERV "
        cd $REMOTE_PATH &&
        $PHP artisan optimize:clear &&
        $PHP artisan vendor:publish --tag=otk-libs-config --force &&
        $PHP artisan config:cache &&
        $PHP artisan route:cache &&
        sudo chown -R www-data:www-data public storage bootstrap/cache &&
        sudo systemctl reload php8.4-fpm
      "

deploy_server_01:
  <<: *deploy_definition
  variables:
    SERV: tgzabbix-01.monitoring.novotelecom.ru

deploy_server_02:
  <<: *deploy_definition
  variables:
    SERV: tgzabbix-02.monitoring.novotelecom.ru
