#!/bin/sh

echo "
APP_NAME=OTK-SERVICE-BOT
APP_ENV=local
APP_KEY=\"$APP_KEY\"
APP_DEBUG=false

APP_LOG=/var/log/otk/vm/bot2/laravel.log
APP_ERR_LOG=/var/log/otk/vm/bot2/laravel.error.log
APP_DBG_LOG=/var/log/otk/vm/bot2/laravel.debug.log
ASSIGNEE=hohlovav@ntk.novotelecom.ru

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US
APP_TIMEZONE=\"Asia/Novosibirsk\"

APP_MAINTENANCE_DRIVER=file

OTK_API_PORT=8000
PING=/bin/ping
TELNET=/usr/bin/telnet
ZABBIX_GET=/usr/bin/zabbix_get
ZABBIX_SEND=/usr/bin/zabbix_sender

PHP_CLI_SERVER_WORKERS=16

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

BROADCAST_CONNECTION=reverb
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=file
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

#REDIS_CLIENT=predis
#REDIS_HOST=\"otk-rm-test.novotelecom.ru\"
#REDIS_PASSWORD=\"$REDIS_PASS\"
#REDIS_PORT=6379

MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS=\"hello@example.com\"
MAIL_FROM_NAME=\"\${APP_NAME}\"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME=\"\${APP_NAME}\"

OTK_API_URL=https://otk-api.novotelecom.ru/api
TFTP_PORT=22

SESSION_DRIVER=file
SESSION_LIFETIME=1440
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null
SESSION_SECURE_COOKIE=true
SESSION_HTTP_ONLY=true
#SESSION_DOMAIN=localhost,novotelecom.ru,otk
AUTH_COOKIE_NAME=auth_token

TELEGRAM_BOT_TOKEN=\"$TELEGRAM_BOT_TOKEN\"
TELEGRAM_PROXY=\"$TELEGRAM_PROXY\"
TELEGRAM_DEBUG=false
TELEGRAM_DEBUG_UIDS=\"$TELEGRAM_DEBUG_UIDS\"

AUTH_METHOD=ldap

LDAP_SCHEMA=ActiveDirectory
LDAP_AUTO_CONNECT=false
LDAP_USE_SSL=false
LDAP_HOSTS=\"otk-haproxy.monitoring.novotelecom.ru\"
LDAP_PORT=50100
LDAP_BASE_DN=\"OU=Users,OU=Ntk,DC=ntk,DC=novotelecom,DC=ru\"
LDAP_USERNAME=\"$OFFICE_LDAP_USER\"
LDAP_PASSWORD=\"$OFFICE_LDAP_PASS\"
LDAP_USER_ATTRIBUTE=samaccountName
LDAP_USER_FILTER=\"(&(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))\"
LDAP_ADM_GROUP=otkadm
LDAP_ADM_PRIVILEGES=15
LDAP_ATTRIBUTES=\"samaccountname name department distinguishedName mobile\"


L5_SWAGGER_VERSION=2.0
L5_SWAGGER_GENERATE_ALWAYS=true
L5_SWAGGER_GENERATE_YAML_COPY=true
L5_SWAGGER_HOST=otk-rm-test.novotelecom.ru
L5_SWAGGER_CONST_HOST=\"https://\${L5_SWAGGER_HOST}/api\"

DB_CONNECTION=ssddb_rm

SSDDB_HOST=10.245.177.89
SSDDB_PORT=6432
SSDDB_DATABASE=userlogs
SSDDB_USER=\"$SSDDB_USER\"
SSDDB_PASS=\"$SSDDB_PASS\"
SSDDB_SCHEMA=public

QGISDB_HOST=172.20.21.242
QGISDB_PORT=5432
QGISDB_DATABASE=gisdb
QGISDB_USER=\"$QGISDB_USER\"
QGISDB_PASS=\"$QGISDB_PASS\"
QGISDB_SCHEMA=qgis

EMRGDB_HOST=10.245.177.24
EMRGDB_PORT=5000
EMRGDB_DATABASE=userlogs
EMRGDB_USER=\"$EMRGDB_USER\"
EMRGDB_PASS=\"$EMRGDB_PASS\"
EMRGDB_SCHEMA=public

ZABBIXDB_DATABASE=zabbix
ZABBIXDB_SCHEMA=zabbix

ZABBIXDB_HOST=zabbix.novotelecom.ru
ZABBIXDB_PORT=50001
ZABBIXDB_USER=\"$ZABBIXDB_USER\"
ZABBIXDB_PASS=\"$ZABBIXDB_PASS\"

OTK_DB_HOST=10.195.0.100
OTK_DB_READ_PORT=50001
OTK_DB_WRITE_PORT=50000
OTK_DB_DATABASE=zabbix-services
OTK_DB_SCHEMA=inventory_history
OTK_DB_USER=\"$OTK_DB_USER\"
OTK_DB_PASS=\"$OTK_DB_PASS\"

ZABBIXDB_OLD_HOST=10.245.176.212
ZABBIXDB_OLD_PORT=5432
ZABBIXDB_OLD_SCHEMA=public
ZABBIXDB_OLD_USER=\"$ZABBIXDB_OLD_USER\"
ZABBIXDB_OLD_PASS=\"$ZABBIXDB_OLD_PASS\"

ZABBIXDB_RESERVE_HOST=10.245.176.16
ZABBIXDB_RESERVE_PORT=5432

ZABBIX_API_OLD_USER=\"$ZABBIX_API_OLD_USER\"
ZABBIX_API_OLD_PASS=\"$ZABBIX_API_OLD_PASS\"
ZABBIX_API_OLD_HOST=https://monitoring.novotelecom.ru/api_jsonrpc.php

ZABBIX_API_HOST=https://zabbix.novotelecom.ru:50101/api_jsonrpc.php
ZABBIX_API_TOKEN=\"$ZABBIX_API_TOKEN\"

COLLECTORDB_HOST=10.245.177.18
COLLECTORDB_PORT=5432
COLLECTORDB_DATABASE=userlogs
COLLECTORDB_USER=\"$COLLECTORDB_USER\"
COLLECTORDB_PASS=\"$COLLECTORDB_PASS\"
COLLECTORDB_SCHEMA=public

NTK_CLICKHOUSE_COLLECTORDB_HOST=otk-clickhouse.monitoring.novotelecom.ru
NTK_CLICKHOUSE_COLLECTORDB_PORT=8123
NTK_CLICKHOUSE_COLLECTORDB_PORT2=9000
NTK_CLICKHOUSE_COLLECTORDB_DATABASE=default
NTK_CLICKHOUSE_COLLECTORDB_USER=\"$NTK_CLICKHOUSE_COLLECTORDB_USER\"
NTK_CLICKHOUSE_COLLECTORDB_PASS=\"$NTK_CLICKHOUSE_COLLECTORDB_PASS\"

# changed 2025-08-04
ASR_USER=\"$ASR_USER\"
ASR_PASS=\"$ASR_PASS\"

A4_USER=\"$A4_USER\"
A4_PASS=\"$A4_PASS\"

BROADWAY_USER=\"$BROADWAY_USER\"
BROADWAY_PASS=\"$BROADWAY_PASS\"
# changed 2025-08-05
BROADWAY_OFFICE_PASS=\"$BROADWAY_OFFICE_PASS\"

CONFLUENCE_USER=\"$CONFLUENCE_USER\"
# changed 2025-08-05
CONFLUENCE_PASS=\"$CONFLUENCE_PASS\"

DPI_USER=\"$DPI_USER\"
DPI_PASS=\"$DPI_PASS\"

INTERCOM_USER=\"$INTERCOM_USER\"
INTERCOM_PASS=\"$INTERCOM_PASS\"

IPAM_USER=\"$IPAM_USER\"
IPAM_PASS=\"$IPAM_PASS\"

JASPER_USER=\"$JASPER_USER\"
JASPER_PASS=\"$JASPER_PASS\"

JIRA_USER=\"$JIRA_USER\"
# changed 2025-08-05
JIRA_PASS=\"$JIRA_PASS\"

MACOVKA_HOST=10.245.176.4
MACOVKA_DATABASE=macovka
MACOVKA_PORT=5432
MACOVKA_USER=\"$MACOVKA_USER\"
MACOVKA_PASS=\"$MACOVKA_PASS\"

RABBIT_USER=\"$RABBIT_USER\"
RABBIT_PASS=\"$RABBIT_PASS\"

# changed 2025-08-04
SHIELD_USER=\"$SHIELD_USER\"
SHIELD_PASS=\"$SHIELD_PASS\"

NTK_NET_HESSIAN_USER=\"$NTK_NET_HESSIAN_USER\"
NTK_NET_HESSIAN_PASS=\"$NTK_NET_HESSIAN_PASS\"
NTK_NET_URI=http://drug/asr-ntk-net
NTK_NET_BROADWAY_A4_NODE_URL=http://broadway2:8070/broadway/dump/?script=house/node/com-node-by-a4node.sql&a4NodeIdInt=
NTK_NET_BROADWAY_USER=\"$NTK_NET_BROADWAY_USER\"
NTK_NET_BROADWAY_PASS=\"$NTK_NET_BROADWAY_PASS\"

V083_SANDBOX_HOST=192.168.154.90
#'latestdb.dev.novotelecom.ru
V083_SANDBOX_DATABASE=v083
V083_SANDBOX_PORT=4100
V083_SANDBOX_USER=sa
V083_SANDBOX_PASS=

BSR_USER=\"$BSR_USER\"
BSR_PASS=\"$BSR_PASS\"

OFFICE_LDAP_USER=\"$OFFICE_LDAP_USER\"
OFFICE_LDAP_PASS=\"$OFFICE_LDAP_PASS\"

REVERB_APP_ID=$REVERB_APP_ID
REVERB_APP_KEY=\"$REVERB_APP_KEY\"
REVERB_APP_SECRET=\"$REVERB_APP_SECRET\"
REVERB_HOST=\"otk-rm-test-02.novotelecom.ru\"
REVERB_SCHEME=\"https\"
REVERB_PORT=null
REVERB_SERVER_HOST=0.0.0.0
REVERB_SERVER_PORT=8889
REVERB_SCALING_ENABLED=true
REVERB_SCALING_DRIVER=redis

VITE_REVERB_PORT=\"\${REVERB_PORT}\"
VITE_REVERB_HOST=\"\${REVERB_HOST}\"
VITE_REVERB_APP_KEY=\"\${REVERB_APP_KEY}\"
VITE_REVERB_SCHEME=\"\${REVERB_SCHEME}\"

" > src/.env
